-- 테이블 생성

-- 카테고리
CREATE TABLE CATEGORY (
    CATEGORY_ID   NUMBER        NOT NULL,
    CATEGORY_NAME VARCHAR2(100) NOT NULL,
    DESCRIPTION   VARCHAR2(500),
    CREATED_AT    DATE          DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_CATEGORY PRIMARY KEY (CATEGORY_ID)
);

COMMENT ON TABLE  CATEGORY              IS '카테고리';
COMMENT ON COLUMN CATEGORY.CATEGORY_ID   IS '카테고리 ID';
COMMENT ON COLUMN CATEGORY.CATEGORY_NAME IS '카테고리명';
COMMENT ON COLUMN CATEGORY.DESCRIPTION   IS '설명';
COMMENT ON COLUMN CATEGORY.CREATED_AT    IS '생성일시';

-- 보관 위치
CREATE TABLE LOCATION (
    LOCATION_ID   NUMBER        NOT NULL,
    LOCATION_NAME VARCHAR2(100) NOT NULL,
    BUILDING      VARCHAR2(100),
    FLOOR         VARCHAR2(20),
    CREATED_AT    DATE          DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_LOCATION PRIMARY KEY (LOCATION_ID)
);

COMMENT ON TABLE  LOCATION              IS '보관 위치';
COMMENT ON COLUMN LOCATION.LOCATION_ID   IS '위치 ID';
COMMENT ON COLUMN LOCATION.LOCATION_NAME IS '위치명';
COMMENT ON COLUMN LOCATION.BUILDING      IS '건물명';
COMMENT ON COLUMN LOCATION.FLOOR         IS '층';
COMMENT ON COLUMN LOCATION.CREATED_AT    IS '생성일시';

-- 물품 마스터
CREATE TABLE ITEM (
    ITEM_ID      NUMBER        NOT NULL,
    CATEGORY_ID  NUMBER        NOT NULL,
    LOCATION_ID  NUMBER        NOT NULL,
    ITEM_NAME    VARCHAR2(200) NOT NULL,
    ITEM_CODE    VARCHAR2(50)  NOT NULL,
    UNIT         VARCHAR2(20)  DEFAULT '개'    NOT NULL,
    MIN_QTY      NUMBER        DEFAULT 0       NOT NULL,
    STATUS       VARCHAR2(10)  DEFAULT 'ACTIVE' NOT NULL,
    CREATED_AT   DATE          DEFAULT SYSDATE  NOT NULL,
    CONSTRAINT PK_ITEM        PRIMARY KEY (ITEM_ID),
    CONSTRAINT FK_ITEM_CAT    FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY(CATEGORY_ID),
    CONSTRAINT FK_ITEM_LOC    FOREIGN KEY (LOCATION_ID) REFERENCES LOCATION(LOCATION_ID),
    CONSTRAINT UQ_ITEM_CODE   UNIQUE (ITEM_CODE),
    CONSTRAINT CK_ITEM_STATUS CHECK (STATUS IN ('ACTIVE', 'INACTIVE'))
);

COMMENT ON TABLE  ITEM             IS '물품 마스터';
COMMENT ON COLUMN ITEM.ITEM_ID     IS '물품 ID';
COMMENT ON COLUMN ITEM.CATEGORY_ID IS '카테고리 ID';
COMMENT ON COLUMN ITEM.LOCATION_ID IS '위치 ID';
COMMENT ON COLUMN ITEM.ITEM_NAME   IS '물품명';
COMMENT ON COLUMN ITEM.ITEM_CODE   IS '물품 코드 (자산번호)';
COMMENT ON COLUMN ITEM.UNIT        IS '단위 (개, 박스 등)';
COMMENT ON COLUMN ITEM.MIN_QTY     IS '최소 재고 수량';
COMMENT ON COLUMN ITEM.STATUS      IS '상태 (ACTIVE/INACTIVE)';
COMMENT ON COLUMN ITEM.CREATED_AT  IS '생성일시';

-- 현재 재고
CREATE TABLE STOCK (
    STOCK_ID    NUMBER NOT NULL,
    ITEM_ID     NUMBER NOT NULL,
    CURRENT_QTY NUMBER DEFAULT 0      NOT NULL,
    UPDATED_AT  DATE   DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_STOCK      PRIMARY KEY (STOCK_ID),
    CONSTRAINT FK_STOCK_ITEM FOREIGN KEY (ITEM_ID) REFERENCES ITEM(ITEM_ID),
    CONSTRAINT UQ_STOCK_ITEM UNIQUE (ITEM_ID),
    CONSTRAINT CK_STOCK_QTY  CHECK (CURRENT_QTY >= 0)
);

COMMENT ON TABLE  STOCK             IS '현재 재고';
COMMENT ON COLUMN STOCK.STOCK_ID    IS '재고 ID';
COMMENT ON COLUMN STOCK.ITEM_ID     IS '물품 ID';
COMMENT ON COLUMN STOCK.CURRENT_QTY IS '현재 재고 수량';
COMMENT ON COLUMN STOCK.UPDATED_AT  IS '최종 수정일시';

-- 입출고 이력
CREATE TABLE STOCK_HISTORY (
    HISTORY_ID   NUMBER        NOT NULL,
    ITEM_ID      NUMBER        NOT NULL,
    HISTORY_TYPE VARCHAR2(3)   NOT NULL,
    QTY          NUMBER        NOT NULL,
    REASON       VARCHAR2(500),
    CREATED_BY   VARCHAR2(100) DEFAULT 'SYSTEM' NOT NULL,
    CREATED_AT   DATE          DEFAULT SYSDATE  NOT NULL,
    CONSTRAINT PK_HISTORY      PRIMARY KEY (HISTORY_ID),
    CONSTRAINT FK_HISTORY_ITEM FOREIGN KEY (ITEM_ID) REFERENCES ITEM(ITEM_ID),
    CONSTRAINT CK_HISTORY_TYPE CHECK (HISTORY_TYPE IN ('IN', 'OUT')),
    CONSTRAINT CK_HISTORY_QTY  CHECK (QTY > 0)
);

COMMENT ON TABLE  STOCK_HISTORY              IS '입출고 이력';
COMMENT ON COLUMN STOCK_HISTORY.HISTORY_ID   IS '이력 ID';
COMMENT ON COLUMN STOCK_HISTORY.ITEM_ID      IS '물품 ID';
COMMENT ON COLUMN STOCK_HISTORY.HISTORY_TYPE IS '유형 (IN: 입고 / OUT: 출고)';
COMMENT ON COLUMN STOCK_HISTORY.QTY          IS '수량';
COMMENT ON COLUMN STOCK_HISTORY.REASON       IS '사유';
COMMENT ON COLUMN STOCK_HISTORY.CREATED_BY   IS '처리자';
COMMENT ON COLUMN STOCK_HISTORY.CREATED_AT   IS '처리일시';