-- 물품 등록 시 STOCK 행을 자동으로 만들어주는 트리거

CREATE OR REPLACE TRIGGER TRG_ITEM_STOCK
AFTER INSERT ON ITEM
FOR EACH ROW
BEGIN
   INSERT INTO STOCK (STOCK_ID, ITEM_ID, CURRENT_QTY, UPDATED_AT)
   VALUES (SEQ_STOCK.NEXTVAL, :NEW.ITEM_ID, 0, SYSDATE);
END;
/