-- 테스트용 샘플 데이터

-- 카테고리
INSERT INTO CATEGORY (CATEGORY_ID, CATEGORY_NAME, DESCRIPTION)
VALUES (SEQ_CATEGORY.NEXTVAL, 'IT장비', '노트북, 모니터 등 IT 관련 장비');

INSERT INTO CATEGORY (CATEGORY_ID, CATEGORY_NAME, DESCRIPTION)
VALUES (SEQ_CATEGORY.NEXTVAL, '사무용품', '볼펜, 노트 등 일반 사무용품');

INSERT INTO CATEGORY (CATEGORY_ID, CATEGORY_NAME, DESCRIPTION)
VALUES (SEQ_CATEGORY.NEXTVAL, '소모품', '복사지, 토너 등 소모성 물품');

-- 위치
INSERT INTO LOCATION (LOCATION_ID, LOCATION_NAME, BUILDING, FLOOR)
VALUES (SEQ_LOCATION.NEXTVAL, 'A창고 1층', 'A동', '1F');

INSERT INTO LOCATION (LOCATION_ID, LOCATION_NAME, BUILDING, FLOOR)
VALUES (SEQ_LOCATION.NEXTVAL, 'B창고 2층', 'B동', '2F');

-- 물품 (INSERT 시 TRG_ITEM_STOCK 트리거로 STOCK 자동 생성됨)
INSERT INTO ITEM (ITEM_ID, CATEGORY_ID, LOCATION_ID, ITEM_NAME, ITEM_CODE, UNIT, MIN_QTY)
VALUES (SEQ_ITEM.NEXTVAL, 1, 1, '노트북 15인치', 'IT-001', '대', 2);

INSERT INTO ITEM (ITEM_ID, CATEGORY_ID, LOCATION_ID, ITEM_NAME, ITEM_CODE, UNIT, MIN_QTY)
VALUES (SEQ_ITEM.NEXTVAL, 1, 1, '모니터 27인치', 'IT-002', '대', 3);

INSERT INTO ITEM (ITEM_ID, CATEGORY_ID, LOCATION_ID, ITEM_NAME, ITEM_CODE, UNIT, MIN_QTY)
VALUES (SEQ_ITEM.NEXTVAL, 2, 2, 'A4 복사지', 'OF-001', '박스', 10);

COMMIT;